<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">


<!--set macro-->
<xacro:property name="width" value="0.02"/>
<xacro:property name="length" value="0.1"/>
<xacro:property name="mass" value="1"/>
<xacro:macro name="default_link" params="name color">
  <link name="${name}">
    <inertial>
      <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
          ixx="${mass / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
          iyy="${mass / 12.0 * (length*length + width*width)}" iyz="0.0"
          izz="${mass / 12.0 * (width*width + length*length)}"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${length} ${width} ${width}"/>
      </geometry>
      <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
      <material name="${color}"/>
    </visual>

    <collision>
      <geometry>
          <box size="${length} ${width} ${width}"/>
      </geometry>
      <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
    </collision>

    
  </link>
</xacro:macro>
<xacro:macro name="revolute_joint" params="name parent child">
  <joint name="${name}" type="continuous">
    <parent link="${parent}"/>
    <child link="${child}"/>
    <origin xyz="0 ${width} ${height1}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>
</xacro:macro>
<material name="black">
  <color rgba="0.0 0.0 0.0 1.0"/>
</material>

<material name="blue">
  <color rgba="0.0 0.0 0.8 1.0"/>
</material>

<material name="green">
  <color rgba="0.0 0.8 0.0 1.0"/>
</material>

<material name="grey">
  <color rgba="0.2 0.2 0.2 1.0"/>
</material>

<material name="orange">
  <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
</material>

<material name="brown">
  <color rgba="${222/255} ${207/255} ${195/255} 1.0"/>
</material>

<material name="red">
  <color rgba="0.8 0.0 0.0 1.0"/>
</material>

<material name="white">
  <color rgba="1.0 1.0 1.0 1.0"/>
</material>


  <xacro:default_link name="link_0" color="red"/>
  <xacro:default_link name="link_1" color="green"/>
  <xacro:default_link name="link_2" color="blue"/>
  
  <joint name="joint_1" type="continuous">
    <parent link="link_0"/>
    <child link="link_1"/>
    <origin xyz="${length} 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="joint_2" type="continuous">
    <parent link="link_1"/>
    <child link="link_2"/>
    <origin xyz="${length} 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>


</robot>

<!--parse file : rosrun xacro xacro inorder -o 3R.urdf 3R.urdf.xacro-->